### ISSUE TITLE
webquiz display problem

### ISSUE THREAD

**Issue by erics68** [AndrewAtLarge/WebQuiz#9] opened 2020-05-02 16:25 UTC
Hi
I would like to use this excellent package. Everything seems to work find except the render : all the caractère writen between $..$ in the tex file are bad displayed in the html page. I'm working with windows. The webquiz program as well been executed. Maybe it's a problem with miktex but if someone has an idea, it would be fine.
With the answer-complex exemple it produce that 
Question 1. If <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline" ><mi >a</mi> <mo class="MathClass-rel">=</mo> <mn>3</mn> <mo class="MathClass-bin">−</mo> <mi >i</mi></math> and <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline" ><mi >b</mi> <mo class="MathClass-rel">=</mo> <mn>2</mn> <mo class="MathClass-bin">+</mo> <mi >i</mi></math> then what is <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline" ><mi >a</mi><mi >b</mi></math>? 
![Capture](https://user-images.githubusercontent.com/64699618/80869677-16015c80-8ca2-11ea-8fb3-062490625314.JPG)

**Comment by AndrewAtLarge** [comment] 2020-05-02 21:09
Thanks for the bug report. This seems to be a new problem that is caused by some recent updates to some of the packages that WebQuiz relies on. I am aware of this problem but I currently flat out with my day job and have not had time to trouble and fix the problem. I will get to this as soon as I can.

**Comment by Andy-Can** [comment] 2020-07-15 17:14
Do you foresee this being resolved by the end of August? Trying to figure out whether it would be a good idea to start writing quizzes for the start of the school year (September).

**Comment by webquiz** [comment] 2020-07-18 03:11
Yes, it should be. I am troubleshooting the problem now and hope to have it fixed soon.

**Comment by AndrewAtLarge** [comment] 2020-07-20 00:28
This turns out to be an upstream bug in LuaXML related to handling of CDATA entries. A fix is now available from the LuaXML git repository. I will close this issue when this is available from TeXLive.

**Comment by Andy-Can** [comment] 2020-07-20 00:51
Awesome. In the intermin, can you describe which files you replaced? Not finding much online about LuaXML.

**Comment by AndrewAtLarge** [comment] 2020-07-20 10:19
Michal Hoftich told me that he will "update it soon, hopefully today". When he does this I will let you know by closing this issue. If you want to update LuaXML yourself you can do this from  https://github.com/michal-h21/LuaXML, but the process is a little involved. Basically, you need to clone the repository, install the dependencies listed on the LuaXML github site and then compile the code.

**Comment by AndrewAtLarge** [comment] 2020-07-20 11:26
The updated version of LuaXML is now available from [ctan](https://www.ctan.org/pkg/luaxml). If you update `luaxml` using tlmgr, for TeXLive, or using the MikTeX console, for MikTeX, then this should solve the problem.

**Closed** 2020-07-20 11:28 UTC
Labels: upstream bug

**Comment by Andy-Can** [comment] 2020-07-22 15:24
Success with this fix. I am getting the following error message, but it doesn't seem to be effecting anything. Figured I'd include for reference. 
<img width="1308" alt="Screen Shot 2020-07-22 at 11 21 47 AM" src="https://user-images.githubusercontent.com/65306284/88195290-de091600-cc0d-11ea-9c86-d45c9b05e2f7.png">
